// Generated by CoffeeScript 1.6.3
var makeTestVerticies;

makeTestVerticies = function() {
  var graph1;
  telescopicText.reset();
  window.startVertex = telescopicText.vertex({
    _name: 'A',
    content: 'For the past four years, ',
    _children: null,
    _next: 'B',
    _remainAfterClick: false,
    _graph: 'graph1',
    _starter: true
  });
  telescopicText.vertex({
    _name: 'B',
    content: 'I\'ve been working at MIT. ',
    _children: [['C', 'E','I', 'D', 'F','G']],
    _remainAfterClick: true,
    _next: 'C',
    _graph: 'graph1',
    _starter: true
  });
  telescopicText.vertex({
    _name: 'C',
    content: '<br /><br />For two of three of those years, I was also getting an ',
    _children: null,
    _remainAfterClick: false,
    _next: 'E',
    _graph: 'graph1',
    _starter: false
  });
  telescopicText.vertex({
    _name: 'D',
    content: '<br /><br />During the most recent year, I\'ve worked as a programmer for the MIT ',
    _children: null,
    _remainAfterClick: false,
    _next: 'F',
    _graph: 'graph1',
    _starter: false
  });
  telescopicText.vertex({
    _name: 'F',
    content: 'CSAIL ',
    _children: [['J']],
    _remainAfterClick: true,
    _next: 'J',
    _graph: 'graph1'
  });
  telescopicText.vertex({
    _name: 'G',
    content: '<a href="http://bigdata.csail.mit.edu" target="_blank">Big Data Initiative</a> <a href="http://livinglab.mit.edu" target="_blank">Living Lab</a>. ',
    _children: null,
    _remainAfterClick: false,
    _next: null,
    _graph: 'graph1'
  });
  telescopicText.vertex({
    _name: 'E',
    content: 'MS ',
    _children: [['H']],
    _remainAfterClick: true,
    _next: 'H',
    _graph: 'graph1',
    _starter: false
  });
  telescopicText.vertex({
    _name: 'H',
    content: 'in Information Systems ',
    _children: null,
    _remainAfterClick: false,
    _next: 'I',
    _graph: 'graph1'
  });
  telescopicText.vertex({
    _name: 'I',
    content: 'from Northeastern University. ',
    _children: null,
    _remainAfterClick: false,
    _next: 'D',
    _graph: 'graph1'
  });
  telescopicText.vertex({
    _name: 'J',
    content: '<a href="http://csail.mit.edu" target="_blank">(Computer Science and Artificial Intelligence Lab)</a> ',
    _children: null,
    _remainAfterClick: false,
    _next: 'G',
    _graph: 'graph1'
  });
  telescopicText.vertex({
    _name: '',
    content: '',
    _children: null,
    _remainAfterClick: false,
    _next: null,
    _graph: 'graph1'
  });
  telescopicText.vertex({
    _name: '',
    content: '',
    _children: null,
    _remainAfterClick: false,
    _next: null,
    _graph: 'graph1'
  });
  telescopicText.vertex({
    _name: '',
    content: '',
    _children: null,
    _remainAfterClick: false,
    _next: null,
    _graph: 'graph1'
  });
  telescopicText.vertex({
    _name: '',
    content: '',
    _children: null,
    _remainAfterClick: false,
    _next: null,
    _graph: 'graph1'
  });
  telescopicText.vertex({
    _name: '',
    content: '',
    _children: null,
    _remainAfterClick: false,
    _next: null,
    _graph: 'graph1'
  });
  telescopicText.vertex({
    _name: '',
    content: '',
    _children: null,
    _remainAfterClick: false,
    _next: null,
    _graph: 'graph1'
  });
  telescopicText.vertex({
    _name: '',
    content: '',
    _children: null,
    _remainAfterClick: false,
    _next: null,
    _graph: 'graph1'
  });
  telescopicText.vertex({
    _name: '',
    content: '',
    _children: null,
    _remainAfterClick: false,
    _next: null,
    _graph: 'graph1'
  });
  telescopicText.vertex({
    _name: '',
    content: '',
    _children: null,
    _remainAfterClick: false,
    _next: null,
    _graph: 'graph1'
  });
  telescopicText.vertex({
    _name: '',
    content: '',
    _children: null,
    _remainAfterClick: false,
    _next: null,
    _graph: 'graph1'
  });
  telescopicText.vertex({
    _name: '',
    content: '',
    _children: null,
    _remainAfterClick: false,
    _next: null,
    _graph: 'graph1'
  });
  telescopicText.vertex({
    _name: '',
    content: '',
    _children: null,
    _remainAfterClick: false,
    _next: null,
    _graph: 'graph1',
    _starter: true
  });
  telescopicText.markup({
    _name: '',
    content: '',
    _children: null,
    _graph: 'graph1',
    _starter: null
  });
  telescopicText.markup({
    _name: '',
    content: '',
    _children: null,
    _graph: 'graph1',
    _starter: null
  });
  graph1 = telescopicText.graphs['graph1'];
  return graph1;
};
